
/* CS50 final project for Spring 2016
    Presented by Hany Bassily*/
    
    
/* Script for E-mail Handling
==============================
*/
// Document set up
$(document).ready(function(event) {
    
    // Allow DOM manipulation without server request
    $('#mailingform').submit(function(event) {
        event.preventDefault();
        
        // Sending an asynchronous mail request using ajax
        $.ajax({
            url:'php/mailcompany.php',
            
            // Data to go inside the e-mail body
            data:
            {
                name: $('#custname').val(),
                email: $('#email').val(),
                phonenum: $('#custphone').val(),
                message: $('#message').val()
            },
            
            // Choosing POST
            type: 'POST',
            
            // Just in case
            cache: false,
            
            // Expecting text from the server
            dataType:'text',
            
            // If the request is successfull callback to change the DOM
            success:function(statdata,status,jqXHR){
                $('#mailingform').html('<div><h2>Success! Mail was Sent</h2><h4>Click <a href="javascript:history.go(0)">Here</a> to dismiss this message</h4></div>');
            },
            
            // Callback if the request is not successful
            error:function(jqXHR,status,error){
                $('#mailingform').html('<div><h2>Sorry!</h2><h4>We were unable to send you message</h4><h3>Click <a href="javascript:history.go(0)">Here</a> to dismiss and try again</h3></div>');
            }
        });
    });
});

/* Scripts to modify the DOM in the information area:
=====================================================
*/

$(document).ready(function(event) {
    
    /*1:Changing the content of the explanation Area:*/
    
    //First Case:
    $('#main').click(function(){
       $('#varsec').html('<h3>Number of Firms:</h3><p>This graph presents the total number of firms. It is important to note that not only this factor should be considered as indicator as it is strongly dependant on the type of the activity and does not refect the actual investement</p>'); 
    });
    
    // Second Case:
    $('#first').click(function(){
       $('#varsec').html('<h3>Number of Establishments:</h3><p>This graph demonstrates the total number of establishments associated with this industry sector. It includes all productive and administrative assets. This number could be more representative of the infrastructure volume than the total number of firms.</p>'); 
    });
    
    // Third Case:
    $('#second').click(function(){
       $('#varsec').html('<h3>Total Employment:</h3><p>This graph demonstrates the total number of full time employed personnel associated with this industry. It ommits other type of employments such as seasonal  and part-time since they are not included as the main workforce since this data is used for the census purpose and reflects the department of labor numbers.</p>');
    });
    
    // Fourth Case:
    $('#third').click(function(){
       $('#varsec').html('<h3>Total Payroll:</h3><p>This graph demonstrates the total amount of payroll gross payment associated with this industry. This indicator could be used as a direct factor of the investment volume of the industry. This data is also used by the department of labor to determine the minimum prevailing wage of a certain ocupation associated with this industry.</p>'); 
    });
    
    // Fifth Case:
    $('#fourth').click(function(){
       $('#varsec').html('<h3>Average Income:</h3><p>This graph is a calculated graph generated by dividing the gross payroll income by the workforce volume. It is an interesting information and can serve as a guide for which sector of the economy is the more lucrative. Enjoy!</p>');    
    });
    
    
    /*2- Displaying a full list of companies*/
    
    $("#clickme").click(function(){
    
        $("#companel").slideToggle();
        $("#grapharea").slideToggle();
        $(".explain").slideToggle();
    });
});

/*Script to Access the Demopage
================================
*/

$(document).ready(function(event){
   $("#loginForm").submit(function(){
       if($("#pswd").val() !== "@1404#2016"){
          $("#authenticationForm").html('<h2 style="margin-bottom:5%;">Invalid Password!</h2><p><h4>Please Click <a href="javascript:history.go(0)">HERE </a> to go back.</h4></p>');
          return false;
       }
       else{
           return true;
       }
   });
   event.preventDefault;
});